import React, { PropsWithChildren } from 'react';
import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
